package edu.uwb.project.encryptedbulletinboard.model;

import javax.persistence.*;
import java.util.Objects;

/**
 * This class serves as a structure for handling the 'Message' component of the application.
 * Every message sent/posted on a board has the following features:
 * - A unique identifier: Every message is assigned an ID.
 * - Text or the Message itself.
 * - BoardID: Represents the ID of the Board on which the message was posted.
 * - Username: Contains the username of a user sending the message.
 * - Key: A key later used in the application to both encrypt and decrypt the message.
 */
@Entity
@Table(name = "messages")
public class MessageModel {

    // Unque Identifier of a Message.
    @Id
    @Column(name = "message_id")
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    Integer id;

    // The message posted.
    String text;

    // Unique Identifier of the Board on which the message was posted.
    Integer boardId;

    // Username of the user posting the message.
    String username;

    /** The key to encrypt and decrypt the message.
    This key is generated by the Encryption Service.*/
    String key;

    //////////// Getter and Setter functions ////////////
    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getText() {
        return text;
    }

    public void setText(String text) {
        this.text = text;
    }

    public Integer getBoardId() {
        return boardId;
    }

    public void setBoardId(Integer boardId) {
        this.boardId = boardId;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getKey() {
        return key;
    }

    public void setKey(String key) {
        this.key = key;
    }
    //////////// End Getter and Setter functions ////////////

    /** A function used to check if the ID, Message sent, ID of the Board, Username of the user
    *  and Key generated for the message of a MessageModel instance are same as those of another
    *  MessageModel instance.*/
    @Override
    public boolean equals(Object o)
    {
        //Checking if the current object is same as the object sent as the parameter.
        if (this == o) return true;
        // If the object sent to function is null, return a false boolean value.
        if (o == null || getClass() != o.getClass()) return false;
        // Transforming the object into type MessageModel.
        MessageModel that = (MessageModel) o;

        // Returns false if either of the attributes are not same.
        return Objects.equals(id, that.id) && Objects.equals(text, that.text) && Objects.equals(boardId, that.boardId) && Objects.equals(username, that.username) && Objects.equals(key, that.key);
    }

    /** A function that returns a string containing a Message's Unique Identifier, the
    Message itself, Unique Identifier of the board, Username of the sender and the Key. */
    @Override
    public String toString() {
        return "MessageModel{" +
                "id=" + id +
                ", text='" + text + '\'' +
                ", boardId=" + boardId +
                ", login='" + username + '\'' +
                ", key='" + key + '\'' +
                '}';
    }
}
